Fix avx512gfni test fail
Caused by multiply overflow when generating test case array.

The failed test cases are:
    core_arch::x86::avx512gfni::tests::test_mm256_gf2p8affine_epi64_epi8
    core_arch::x86::avx512gfni::tests::test_mm256_gf2p8mul_epi8
    core_arch::x86::avx512gfni::tests::test_mm256_mask_gf2p8mul_epi8
    core_arch::x86::avx512gfni::tests::test_mm256_maskz_gf2p8mul_epi8
    core_arch::x86::avx512gfni::tests::test_mm512_gf2p8affine_epi64_epi8
    core_arch::x86::avx512gfni::tests::test_mm512_gf2p8mul_epi8
    core_arch::x86::avx512gfni::tests::test_mm512_mask_gf2p8mul_epi8
    core_arch::x86::avx512gfni::tests::test_mm512_maskz_gf2p8mul_epi8
    core_arch::x86::avx512gfni::tests::test_mm_gf2p8affine_epi64_epi8
    core_arch::x86::avx512gfni::tests::test_mm_gf2p8mul_epi8
    core_arch::x86::avx512gfni::tests::test_mm_mask_gf2p8mul_epi8
    core_arch::x86::avx512gfni::tests::test_mm_maskz_gf2p8mul_epi8
    ---- core_arch::x86::avx512gfni::tests::test_mm256_gf2p8affine_epi64_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm256_gf2p8affine_epi64_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- core_arch::x86::avx512gfni::tests::test_mm256_gf2p8mul_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm256_gf2p8mul_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm256_mask_gf2p8mul_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm256_mask_gf2p8mul_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm256_maskz_gf2p8mul_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm256_maskz_gf2p8mul_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm512_gf2p8affine_epi64_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm512_gf2p8affine_epi64_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm512_gf2p8mul_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm512_gf2p8mul_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm512_mask_gf2p8mul_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm512_mask_gf2p8mul_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm512_maskz_gf2p8mul_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm512_maskz_gf2p8mul_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm_gf2p8affine_epi64_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm_gf2p8affine_epi64_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm_gf2p8mul_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm_gf2p8mul_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm_mask_gf2p8mul_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm_mask_gf2p8mul_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24

---- core_arch::x86::avx512gfni::tests::test_mm_maskz_gf2p8mul_epi8 stdout ----
thread 'core_arch::x86::avx512gfni::tests::test_mm_maskz_gf2p8mul_epi8' panicked at 'attempt to multiply with overflow', crates\core_arch\src\x86\avx512gfni.rs:822:24